export const ALTA = [
    /* 19/06/20 */
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-0', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: false, },
        { text: 'E-mail socio', value: false, },
        { text: 'Tutor', value: false, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-1', },
        { spec: '- Forma de pago: Tarjeta' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: false, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-2', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Sin karate' },
        { text: 'Teléfono socio', value: false, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-3', },
        { spec: '- Forma de pago: Efectivo' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: true, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-4', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: true, },
        { text: 'Contacto 1', value: true, },
        { text: 'Teléfono contacto 1', value: true, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-5', },
        { spec: '- Forma de pago: Efectivo' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: true, },
        { text: 'Contacto 1', value: true, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: true, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-6', },
        { spec: '- Forma de pago: Tarjeta' },
        { spec: '- Tarifa: Sin karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: true, },
        { text: 'Contacto 1', value: true, },
        { text: 'Teléfono contacto 1', value: true, },
        { text: 'E-mail contacto 1', value: true, },
        { text: 'Contacto 2', value: true, },
        { text: 'Teléfono contacto 2', value: true, },
        { text: 'E-mail contacto 2', value: true, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-7', },
        { spec: '- Forma de pago: Efectivo' },
        { spec: '- Tarifa: Sin karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: false, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: true, },
        { text: 'Teléfono contacto 1', value: true, },
        { text: 'E-mail contacto 1', value: true, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-9', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: false, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: true, },
        { text: 'Teléfono contacto 1', value: true, },
        { text: 'E-mail contacto 1', value: true, },
        { text: 'Contacto 2', value: true, },
        { text: 'Teléfono contacto 2', value: true, },
        { text: 'E-mail contacto 2', value: true, },
    ],
    /* 05/08/20 */
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-10', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Foto', value: true, },
        { text: 'Teléfono socio', value: false, },
        { text: 'E-mail socio', value: false, },
        { text: 'Tutor', value: false, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-11', },
        { spec: '- Forma de pago: Tarjeta' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Foto', value: true, },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: false, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: false, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-12', },
        { spec: '- Forma de pago: Domiciliación (incluye iban)' },
        { spec: '- Tarifa: Sin karate' },
        { text: 'Foto', value: true, },
        { text: 'Teléfono socio', value: false, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: false, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
    [
        { title: 'Alta de socio', desc: 'Da de alta un socio con la siguientes características:', testName: 'test-alta-13', },
        { spec: '- Forma de pago: Efectivo' },
        { spec: '- Tarifa: Con karate' },
        { text: 'Foto', value: true, },
        { text: 'Teléfono socio', value: true, },
        { text: 'E-mail socio', value: true, },
        { text: 'Tutor', value: true, },
        { text: 'Teléfono tutor', value: true, },
        { text: 'E-mail tutor', value: true, },
        { text: 'Contacto 1', value: false, },
        { text: 'Teléfono contacto 1', value: false, },
        { text: 'E-mail contacto 1', value: false, },
    ],
]
