export const EDITAR = [
    /* 19/06/20 */
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-0', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener tutor' },
        { spec: '- Modifica datos base del socio: nombre, dirección, dni, tarifa o forma de pago' },
        { spec: '- Modifica datos base del tutor: nombre, dirección o dni' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-1', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener contacto' },
        { spec: '- Modifica datos dinámicos del socio: teléfonos o e-mails' },
        { spec: '- Modifica datos base de uno o varios contactos: nombre' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-2', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener contacto' },
        { spec: '- Modifica datos dinámicos de uno o varios contactos: teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-3', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio NO debe tener tutor' },
        { spec: '- Modificar fecha de nacimiento para que el socio sea menor' },
        { spec: '- Añade datos del tutor' },
        { spec: '- Modifica datos base del socio: nombre, dirección, dni, tarifa o forma de pago' },
        { spec: '- Modifica datos dinámicos del socio: teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-4', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio NO debe tener tutor' },
        { spec: '- Modificar fecha de nacimiento para que el socio sea menor' },
        { spec: '- Añade datos del tutor' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-5', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- Modificar la tarifa, si es con karate que pase a sin karate o al revés' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-6', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio NO debe tener forma de pago domiciliada' },
        { spec: '- Modificar la forma de pago, indica domiciliación' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-7', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- Añade datos dinámicos a socio: teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-8', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener tutor' },
        { spec: '- Añade datos dinámicos a tutor: teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-9', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener contacto' },
        { spec: '- Añade datos dinámicos a uno o varios contactos: teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-10', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- Añade un contacto, rellena en él los datos que quieras' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-11', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener teléfonos o e-mails' },
        { spec: '- Elimina uno o varios teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-12', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener teléfonos o e-mails' },
        { spec: '- Elimina varios teléfonos o e-mails' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-13', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener tutor que tenga teléfonos o e-mails' },
        { spec: '- Elimina uno o varios teléfonos o e-mails del tutor' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-14', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener contactos que tengan teléfonos o e-mails' },
        { spec: '- Elimina uno o varios teléfonos o e-mails del contacto' },
    ],
    [
        { title: 'Editar un socio', desc: 'Desde la ficha de cualquier socio realiza modificaciones a sus datos:', testName: 'test-edit-15', },
        { spec: '- No modifiques los cinturones' },
        { spec: '- No modifiques los pagos' },
        { spec: '- El socio debe tener contactos' },
        { spec: '- Elimina uno o varios contactos' },
    ],
]
